import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    setupFiles: './vitest.setup.ts',
    globals: true,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      exclude: [
        'node_modules/',
        './*/*.d.ts',
        './*/*.js',
        './*/*.mjs',
        './*/*.cjs',
        './*/*.config.ts',
        './*/*.config.js',
        './*/*.config.mjs',
        './*/*.config.cjs',
        './*/*.setup.ts',
        './*/*.setup.js',
        './*/*.setup.mjs',
        './*/*.setup.cjs',
        './*/*.d.ts',
        './*/*.js',
        './*/*.mjs',
        './*/*.cjs',
        './*/*.config.ts',
        './*/*.config.js',
        './*/*.config.mjs',
        './*/*.config.cjs',
        './*/*.setup.ts',
        './*/*.setup.js',
        './*/*.setup.mjs',
        './*/*.setup.cjs',
        './src/app/api/**',
        './src/middleware.ts',
        './src/auth.ts',
        './src/lib/db.ts',
        './src/lib/authOptions.ts',
        './src/lib/password.ts',
        './src/lib/logger.ts',
        './src/lib/audit.ts',
        './src/lib/qrcode.ts',
        './src/lib/subdomain.ts',
        './src/lib/templates.ts',
        './src/app/layout.tsx',
        './src/app/page.tsx',
        './src/app/globals.css',
        './src/app/robots.ts',
        './src/app/sitemap.ts',
        './src/components/ui/**',
        './src/components/providers/**',
      ],
    },
  },
})